# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-04-30 08:23
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('publish', '0002_member_poll'),
    ]

    operations = [
        migrations.AddField(
            model_name='member',
            name='alamat',
            field=models.TextField(blank=True, null=True),
        ),
    ]
