# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-04-30 08:24
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('publish', '0003_member_alamat'),
    ]

    operations = [
        migrations.RenameField(
            model_name='member',
            old_name='alamat',
            new_name='alamat_palsu',
        ),
    ]
